(function(){
  const KEY='cora2027_fechamento_reajustes_v2';
  const API='https://script.google.com/macros/s/AKfycbwSpAtBgMjFyQ7J5yUxIfobEt0CxCGNgWEQZxp-mj9z-9zfWIcV2ig9iQlGzcCL5UYk/exec';
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
  const pct=v=>(Number(v)||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+'%';
  const now=()=>new Date().toLocaleString('pt-BR',{timeZone:'America/Fortaleza'});
  const n=v=>Number(String(v??'').replace(',','.'))||0;
  const STI=[
    {id:'STI|INFANTIL',segment:'Educação Infantil',item:'STI Educação Infantil',v26:727.00,detail:'Tempo Integral'},
    {id:'STI|INFANTIL-ESC',segment:'Educação Infantil',item:'STI + Escolaridade Infantil',v26:1164.04,detail:'Tempo Integral + Escolaridade'},
    {id:'STI|FUNDAMENTAL',segment:'Fundamental',item:'STI Fundamental',v26:737.00,detail:'Tempo Integral'},
    {id:'STI|FUNDAMENTAL-ESC',segment:'Fundamental',item:'STI + Escolaridade Fundamental',v26:1201.42,detail:'Tempo Integral + Escolaridade'},
    {id:'STI|FARDA-BLUSA',segment:'STI / Integral',item:'Farda STI - Blusa',v26:57.00,detail:'Fardamento STI'},
    {id:'STI|FARDA-SHORT',segment:'STI / Integral',item:'Farda STI - Short',v26:67.00,detail:'Fardamento STI'}
  ];
  function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch(e){return {}}}
  function write(db){localStorage.setItem(KEY,JSON.stringify(db))}
  async function post(payload){try{await fetch(API,{method:'POST',mode:'no-cors',cache:'no-store',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});return true}catch(e){return false}}
  function toast(msg,type='ok'){let el=document.getElementById('stiToast');if(!el){el=document.createElement('div');el.id='stiToast';document.body.appendChild(el)}el.className='sti-toast '+type;el.textContent=msg;el.style.display='block';clearTimeout(el._t);el._t=setTimeout(()=>el.style.display='none',3200)}
  function rec(row){const db=read(),s=(db.records||{})[row.id];return s||{rate:5,v27:row.v26*1.05,saved:false,savedAt:''}}
  async function saveSti(row,rate,v27,silent=false){const db=read();db.records=db.records||{};db.history=db.history||[];rate=n(rate);v27=n(v27);const stamp=now();db.records[row.id]={rate,v27,saved:true,savedAt:stamp,category:'STI / Tempo Integral',segment:row.segment,item:row.item,detail:row.detail,v26:row.v26};db.history.unshift({at:stamp,category:'STI / Tempo Integral',segment:row.segment,item:row.item,v26:row.v26,v27,rate});if(db.history.length>500)db.history=db.history.slice(0,500);write(db);
    await post({action:'salvarRegistro',aba:'Produtos 2027',id:row.id,data:{'Categoria':'STI / Tempo Integral','Segmento/Turma':row.segment,'Produto':row.item,'Descrição':row.detail,'Valor 2026':row.v26,'Valor 2027':v27,'Reajuste %':rate,'Parcelamento':'','Obrigatório':'NÃO','Status':'RASCUNHO','Aprovado em':'','Publicado no Cora Família':'NÃO','ID':row.id,'Observação':'Salvo no fechamento em '+stamp}});
    if(!silent)toast('✅ '+row.item+' salvo e enviado à planilha.');
  }
  function stiHtml(){return `<div class="adj-block sti-closing-block"><div class="adj-head"><div><h3>🏫 STI / Tempo Integral</h3><small>Fechamento oficial dos valores do Serviço de Tempo Integral. O quantitativo continua sendo informado na Receita para calcular o potencial total.</small></div><button id="saveAllSti">Salvar STI</button></div><div class="adj-table-wrap"><table class="adj-table"><thead><tr><th>Segmento</th><th>Produto</th><th>Detalhe</th><th>2026</th><th>Reajuste %</th><th>Valor 2027</th><th>Status</th><th>Ação</th></tr></thead><tbody>${STI.map(row=>{const r=rec(row);return `<tr class="sti-row" data-id="${row.id}"><td>${row.segment}</td><td><b>${row.item}</b></td><td>${row.detail}</td><td>${money(row.v26)}</td><td><input class="sti-rate" type="number" step="0.01" value="${Number(r.rate).toFixed(2)}"></td><td><input class="sti-v27" type="number" step="0.01" value="${Number(r.v27).toFixed(2)}"></td><td><span class="adj-status ${r.saved?'ok':'pending'}">${r.saved?'SALVO':'PENDENTE'}</span>${r.savedAt?`<small>${r.savedAt}</small>`:''}</td><td><button class="sti-save-row">💾 Salvar</button></td></tr>`}).join('')}</tbody></table></div><div class="sti-info"><b>Como funciona:</b> aqui fechamos o <b>preço oficial 2027</b> de cada produto STI. Na aba Receita, o sistema usa <b>Preço 2027 × Quantidade</b> para chegar ao valor final/potencial de cada produto.</div></div>`}
  function bindSti(block){block.querySelectorAll('.sti-rate').forEach(inp=>inp.addEventListener('input',e=>{const tr=e.target.closest('tr'),row=STI.find(x=>x.id===tr.dataset.id),rate=n(e.target.value);tr.querySelector('.sti-v27').value=(row.v26*(1+rate/100)).toFixed(2);const st=tr.querySelector('.adj-status');st.textContent='ALTERADO';st.className='adj-status changed'}));block.querySelectorAll('.sti-v27').forEach(inp=>inp.addEventListener('input',e=>{const tr=e.target.closest('tr'),row=STI.find(x=>x.id===tr.dataset.id),v=n(e.target.value);tr.querySelector('.sti-rate').value=((v/row.v26-1)*100).toFixed(2);const st=tr.querySelector('.adj-status');st.textContent='ALTERADO';st.className='adj-status changed'}));block.querySelectorAll('.sti-save-row').forEach(btn=>btn.onclick=async()=>{const tr=btn.closest('tr'),row=STI.find(x=>x.id===tr.dataset.id);btn.disabled=true;await saveSti(row,tr.querySelector('.sti-rate').value,tr.querySelector('.sti-v27').value);btn.disabled=false;ensureSti(true)});const all=block.querySelector('#saveAllSti');if(all)all.onclick=async()=>{all.disabled=true;for(const tr of block.querySelectorAll('.sti-row')){const row=STI.find(x=>x.id===tr.dataset.id);await saveSti(row,tr.querySelector('.sti-rate').value,tr.querySelector('.sti-v27').value,true)}toast('☁️ Todos os valores do STI foram salvos e enviados à planilha.');all.disabled=false;ensureSti(true)}}
  function ensureSti(force=false){const sec=document.getElementById('fechamento2027');if(!sec)return;let old=sec.querySelector('.sti-closing-block');if(old&&!force)return;if(old)old.remove();const temp=document.createElement('div');temp.innerHTML=stiHtml();const block=temp.firstElementChild;const history=[...sec.querySelectorAll('.adj-block')].find(x=>x.textContent.includes('Histórico recente'));if(history)sec.insertBefore(block,history);else sec.appendChild(block);bindSti(block);ensurePdfActions()}

  async function pdfLib(){if(window.jspdf?.jsPDF)return window.jspdf.jsPDF;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://unpkg.com/jspdf@4.2.1/dist/jspdf.umd.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)});return window.jspdf.jsPDF}
  async function img(src){try{const r=await fetch(src,{cache:'no-store'}),b=await r.blob();return await new Promise((res,rej)=>{const f=new FileReader();f.onload=()=>res(f.result);f.onerror=rej;f.readAsDataURL(b)})}catch(e){return null}}
  function bases(){try{return (window.TUITION||TUITION||[]).map(r=>({segmento:r.segmento,due26:Number(r.due26)||0,late26:Number(r.late26)||0}))}catch(e){return []}}
  function mats(){try{return window.MATERIALS||MATERIALS||[]}catch(e){return []}}
  function unis(){try{return window.UNIFORMS||UNIFORMS||[]}catch(e){return []}}
  async function gerarPdf(){const trigger=document.getElementById('downloadFinalClosingPdf')||document.getElementById('downloadClosingPdfTop');if(trigger){trigger.disabled=true;trigger.dataset.old=trigger.innerHTML;trigger.textContent='Gerando PDF...'}try{const JsPDF=await pdfLib(),doc=new JsPDF({unit:'mm',format:'a4',compress:true}),W=210,M=14,navy=[11,45,92],blue=[23,103,176],green=[22,128,71],gray=[88,112,139],light=[242,247,252],amber=[166,107,0];let y=16;const logo=await img('logo-escola-web.png'),consult=await img('logo-pdf-web.png');
    function footer(){const p=doc.getNumberOfPages();doc.setPage(p);doc.setFontSize(7);doc.setTextColor(130,145,160);doc.text('Colégio Cora Coralina • Fechamento 2027',M,291);doc.text('Página '+p,W-M,291,{align:'right'})}
    function newPage(title,sub){footer();doc.addPage();y=18;doc.setFillColor(...navy);doc.roundedRect(M,y,W-2*M,18,3,3,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text(title,M+6,y+7);doc.setFont('helvetica','normal');doc.setFontSize(8);if(sub)doc.text(sub,M+6,y+13);y+=25}
    function sectionTitle(t){doc.setTextColor(...navy);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text(t,M,y);y+=5;doc.setDrawColor(200,216,232);doc.line(M,y,W-M,y);y+=5}
    function row(cols,widths,head=false){const h=8;if(y+h>280)newPage('CONTINUAÇÃO DO RELATÓRIO','Tabela continuada');let x=M;if(head){doc.setFillColor(...blue);doc.rect(M,y,W-2*M,h,'F');doc.setTextColor(255);doc.setFont('helvetica','bold')}else{doc.setTextColor(42,58,74);doc.setFont('helvetica','normal');if(Math.round(y/8)%2===0){doc.setFillColor(249,251,254);doc.rect(M,y,W-2*M,h,'F')}}doc.setFontSize(7.1);cols.forEach((t,i)=>{doc.text(String(t),x+2,y+5.2,{maxWidth:widths[i]-4});x+=widths[i]});y+=h}
    if(logo)doc.addImage(logo,'PNG',M,y,23,23,undefined,'FAST');if(consult)doc.addImage(consult,'PNG',170,y,23,23,undefined,'FAST');doc.setTextColor(...navy);doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text('COLÉGIO CORA CORALINA',42,y+7);doc.setFontSize(21);doc.text('Fechamento Oficial 2027',42,y+17);doc.setFont('helvetica','normal');doc.setFontSize(8.5);doc.setTextColor(...gray);doc.text('Mensalidades, materiais, fardamento e STI / Tempo Integral',42,y+23);y=48;doc.setFillColor(...navy);doc.roundedRect(M,y,W-2*M,24,4,4,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(14);doc.text('RELATÓRIO FINAL DE FECHAMENTO',M+7,y+9);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text('Matrículas 2027 • Consolidado da gestão',M+7,y+16);doc.setFontSize(7.5);doc.text('Gerado em '+now(),M+7,y+21);
    const D=read();D.tuition=D.tuition||{};D.records=D.records||{};const B=bases(),matIds=mats().map(r=>'L|'+r.segment+'|'+r.name),uniIds=unis().map((r,i)=>'F|'+i+'|'+r.segment+'|'+r.name),stiIds=STI.map(r=>r.id),all=[...matIds,...uniIds,...stiIds];const savedT=B.filter(x=>D.tuition[x.segmento]?.saved).length,savedI=all.filter(id=>D.records[id]?.saved).length,total=B.length+all.length,saved=savedT+savedI;y=82;sectionTitle('VISÃO GERAL DO FECHAMENTO');[['Segmentos',B.length],['Registros',total],['Salvos',saved],['Pendentes',total-saved]].forEach((c,i)=>{const x=M+i*45;doc.setFillColor(...light);doc.roundedRect(x,y,41,20,2,2,'F');doc.setTextColor(...gray);doc.setFontSize(7);doc.text(c[0],x+4,y+6);doc.setTextColor(...navy);doc.setFont('helvetica','bold');doc.setFontSize(14);doc.text(String(c[1]),x+4,y+15)});y+=30;doc.setFillColor(saved===total?236:255,saved===total?247:247,saved===total?241:226);doc.roundedRect(M,y,W-2*M,23,3,3,'F');doc.setTextColor(...navy);doc.setFontSize(10);doc.text(saved===total?'FECHAMENTO COMPLETO':'FECHAMENTO PARCIAL',M+6,y+8);doc.setFont('helvetica','normal');doc.setTextColor(...gray);doc.setFontSize(8);doc.text(saved+' de '+total+' registros salvos; '+(total-saved)+' pendentes.',M+6,y+15);
    newPage('1. MENSALIDADES E PLANOS 2027','Anuidade, reajuste, 1ª parcela e condições Plano A / Plano B');row(['Segmento','Anuidade 2026','Reajuste','Anuidade 2027','1ª parcela','Plano A 12x','Plano B 11x','Status'],[34,25,17,27,23,24,24,18],true);B.forEach(base=>{const r=D.tuition[base.segmento]||{},rate=Number(r.rate)||0,ann=Number(r.annuity)||base.due26*(1+rate/100),first=Number(r.first)||0,a=Number(r.planA)||Math.max(0,ann-first)/12,b=Number(r.planB)||Math.max(0,ann-first)/11;row([base.segmento,money(base.due26),pct(rate),money(ann),money(first),money(a),money(b),r.saved?'SALVO':'PENDENTE'],[34,25,17,27,23,24,24,18])});y+=8;sectionTitle('ANUIDADE APÓS O VENCIMENTO');row(['Segmento','2026 após venc.','Reajuste','2027 após venc.'],[48,47,28,59],true);B.forEach(base=>{const r=D.tuition[base.segmento]||{},rate=Number(r.rate)||0;row([base.segmento,money(base.late26),pct(rate),money(base.late26*(1+rate/100))],[48,47,28,59])});
    newPage('2. MATERIAIS E LIVROS','Valores-base, reajustes e valores fechados para 2027');row(['Segmento','Produto','2026','Reajuste','2027','Status'],[38,62,25,20,25,22],true);mats().forEach(r=>{const id='L|'+r.segment+'|'+r.name,s=D.records[id]||{},rate=Number(s.rate??0),v=Number(s.v27)||Number(r.v26)*(1+rate/100);row([r.segment,r.name,money(r.v26),pct(rate),money(v),s.saved?'SALVO':'PENDENTE'],[38,62,25,20,25,22])});
    newPage('3. FARDAMENTO','Valores oficiais por segmento e produto');row(['Segmento','Produto','2026','Reajuste','2027','Status'],[38,62,25,20,25,22],true);unis().forEach((r,i)=>{const id='F|'+i+'|'+r.segment+'|'+r.name,s=D.records[id]||{},rate=Number(s.rate??0),v=Number(s.v27)||Number(r.v26)*(1+rate/100);row([r.segment,r.name,money(r.v26),pct(rate),money(v),s.saved?'SALVO':'PENDENTE'],[38,62,25,20,25,22])});
    newPage('4. STI / TEMPO INTEGRAL','Preços oficiais 2027. O quantitativo e o potencial financeiro permanecem na Receita.');row(['Segmento','Produto','2026','Reajuste','2027','Status'],[38,62,25,20,25,22],true);STI.forEach(r=>{const s=D.records[r.id]||{},rate=Number(s.rate??5),v=Number(s.v27)||r.v26*(1+rate/100);row([r.segment,r.item,money(r.v26),pct(rate),money(v),s.saved?'SALVO':'PENDENTE'],[38,62,25,20,25,22])});
    newPage('5. SITUAÇÃO FINAL E APROVAÇÃO','Conferência administrativa antes da publicação para as famílias');doc.setFillColor(saved===total?236:255,saved===total?247:247,saved===total?241:226);doc.roundedRect(M,y,W-2*M,35,4,4,'F');doc.setTextColor(saved===total?green:amber);doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text(saved===total?'FECHAMENTO COMPLETO':'FECHAMENTO PARCIAL',M+7,y+12);doc.setTextColor(...navy);doc.setFontSize(10);doc.text(saved+' registros salvos de '+total,M+7,y+21);doc.setFont('helvetica','normal');doc.setTextColor(...gray);doc.setFontSize(8.5);doc.text((total-saved)+' registro(s) ainda pendente(s) de fechamento.',M+7,y+28);y+=55;doc.setTextColor(...navy);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('APROVAÇÕES',M,y);y+=20;doc.setDrawColor(145,165,185);doc.line(M,y,M+78,y);doc.line(W-M-78,y,W-M,y);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(...gray);doc.text('Responsável pela elaboração',M,y+6);doc.text('Direção / Financeiro',W-M-78,y+6);for(let p=1;p<=doc.getNumberOfPages();p++){doc.setPage(p);doc.setFontSize(7);doc.setTextColor(130,145,160);doc.text('Colégio Cora Coralina • Fechamento 2027',M,291);doc.text('Página '+p+' de '+doc.getNumberOfPages(),W-M,291,{align:'right'})}doc.save('Relatorio-Final-Fechamento-2027-STI.pdf')
  }catch(e){console.error(e);alert('Não foi possível gerar o relatório final agora.')}finally{if(trigger){trigger.disabled=false;trigger.innerHTML=trigger.dataset.old||'📄 Baixar relatório final de fechamento'}}}
  function ensurePdfActions(){const sec=document.getElementById('fechamento2027');if(!sec)return;let bottom=document.getElementById('downloadFinalClosingPdf');if(!bottom){const box=document.createElement('div');box.className='final-report-box sti-final-report';box.innerHTML=`<div><small>RELATÓRIO OFICIAL</small><h3>Fechamento final de valores 2027</h3><p>Mensalidades, materiais, fardamento e STI / Tempo Integral, cada situação em páginas próprias.</p></div><button id="downloadFinalClosingPdf">📄 Baixar relatório final de fechamento</button>`;sec.appendChild(box);bottom=box.querySelector('button')}bottom.dataset.layoutV2='1';bottom.onclick=gerarPdf;const actions=sec.querySelector('.adj-actions');if(actions&&!document.getElementById('downloadClosingPdfTop')){const top=document.createElement('button');top.id='downloadClosingPdfTop';top.textContent='📄 PDF fechamento final';top.onclick=gerarPdf;actions.appendChild(top)}}
  function style(){if(document.getElementById('sti-v29-style'))return;const s=document.createElement('style');s.id='sti-v29-style';s.textContent=`.sti-closing-block{border-top:4px solid #6a4bc3}.sti-closing-block .adj-head small{display:block;color:#61758b;max-width:760px;margin-top:4px}.sti-info{margin:14px 0 0;padding:12px 14px;border-radius:11px;background:#f4f0ff;color:#4d3a7c;border-left:4px solid #6a4bc3}.sti-toast{position:fixed;right:18px;bottom:18px;z-index:99999;max-width:420px;padding:13px 16px;border-radius:12px;background:#168047;color:#fff;font-weight:800;box-shadow:0 10px 28px #0003;display:none}.sti-toast.warn{background:#a86b00}#downloadClosingPdfTop{background:#7b3fc6!important;color:#fff!important;border:0!important;border-radius:11px!important;padding:11px 14px!important;font-weight:900!important;cursor:pointer!important}.sti-final-report{margin-top:24px!important}`;document.head.appendChild(s)}
  function init(){style();ensureSti();ensurePdfActions();new MutationObserver(()=>{ensureSti();ensurePdfActions()}).observe(document.body,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();